---
# ansible-galaxy install -r requirements.yml
roles:
  - src: geerlingguy.docker
  # - src: juju4.falco
# collections:
# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html
# - name: containers.podman
#   version: 1.12.0
