services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2-amd64
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - ELASTIC_PASSWORD=Admin1Admin1
      - KIBANA_PASSWORD=Admin1Admin1
      - LICENSE=basic
      # - LICENSE=trial
      - ES_PORT=9200
      - KIBANA_PORT=5601
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2-amd64
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Admin1Admin1
    ports:
      - 5601:5601
      - 80:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2-amd64
    container_name: logstash
    environment:
      - node.name=logstash
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    ports:
      - 8080:8080
      - 5044:5044
    restart: always

volumes:
  es-data:
