services:
  www:
    container_name: www
    build:
      context: .
    restart: always
    volumes:
      - ./config.inc.php:/var/www/html/config/config.inc.php:ro
    depends_on:
      - mariadb
    ports:
      - 8002:80

  mariadb:
    container_name: mariadb
    image: mariadb:11.3.2
    env_file: dvwa.env
    volumes:
      - mariadb-data:/var/lib/mysql/data
    restart: always

  nginx:
    container_name: nginx
    image: cgr.dev/chainguard/nginx
    restart: always
    ports:
      - 80:8000
      - 443:8443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - www

  modsecurity:
    container_name: modsecurity
    image: owasp/modsecurity-crs:nginx-alpine
    user: root
    restart: always
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx_html:/usr/share/nginx/html
      - ./default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro
    environment:
      - BACKEND=http://www:80
      - PORT=8000
      - SET_REAL_IP_FROM=X-Forwarded-For
      - REAL_IP_HEADER=X-Forwarded-For
      - SET_REAL_IP_FROM=nginx
      - ACCESSLOG=/dev/null
      - ERRORLOG=/var/log/nginx/alerts.log
      - MODSEC_AUDIT_STORAGE=/var/log/nginx/
      - MODSEC_AUDIT_LOG=/var/log/nginx/modsecurity.log
      - BLOCKING_PARANOIA=2
      - EXECUTING_PARANOIA=2
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - MODSEC_RULE_ENGINE=on
      - MODSEC_REQ_BODY_ACCESS=on
    ports:
      - 8001:8000

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    restart: always
    volumes:
      - "/var/log/nginx:/var/log/nginx:ro"
      # Bind-mount a custom configuration file
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    # command: filebeat -e -strict.perms=false
    network_mode: host
    depends_on:
      - nginx

  fluentbit:
    container_name: fluentbit
    image: cr.fluentbit.io/fluent/fluent-bit:3.0.0
    user: root
    volumes:
      - /var/log/:/var/log/
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro

volumes:
  mariadb-data:
