version: "3.9"
services:
  www:
    build:
      context: .
    restart: always
    volumes:
      - ./config.inc.php:/var/www/html/config/config.inc.php:ro
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.7
    env_file: dvwa.env
    volumes:
       - mariadb-data:/var/lib/mysql/data
    restart: always

  nginx:
    image: cgr.dev/chainguard/nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/logs/nginx:/var/logs/nginx
    depends_on:
      - www

  modsecurity:
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    volumes:
      - "/var/logs/nginx:/var/logs/nginx:rw"
    environment:
      - BACKEND=http://www:80
      - PORT=8000
      - SET_REAL_IP_FROM=X-Forwarded-For
      - REAL_IP_HEADER=X-Forwarded-For
      - ACCESSLOG=/dev/null
      - ERRORLOG=/var/logs/nginx/alerts.log
      - BLOCKING_PARANOIA=3
      - MODSEC_AUDIT_STORAGE=/var/logs/nginx/
      - MODSEC_AUDIT_LOG=/var/logs/nginx/modsecurity.log

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    restart: always
    volumes:
      - "/var/logs/nginx:/var/logs/nginx:ro"
      # Bind-mount a custom configuration file
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    # command: filebeat -e -strict.perms=false
    network_mode: host
    depends_on:
      - nginx

volumes:
  mariadb-data:
