---
- name: Deploy ELK
  hosts: elk
  become: true

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: podman
        update_cache: true

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/opt/elk/"
      with_fileglob:
        - "files/elk/*"
      notify:
        - logstash-restart

    - name: trigger logstash-restart
      command: /bin/true
      notify: logstash-restart

    - name: Configure ELK
      block:
        - name: Create a podman network
          containers.podman.podman_network:
            name: elk_network

        - name: Run logstash
          containers.podman.podman_container:
            name: logstash
            image: docker.elastic.co/logstash/logstash:8.7.0-amd64
            state: started
            privileged: false
            env:
              node.name: logstash
            volumes:
              - "/opt/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
            ports:
              - 8080:8080
              - 5044:5044
            network: elk_network
            restart_policy: always

        - name: Run kibana
          containers.podman.podman_container:
            name: kibana
            image: docker.elastic.co/kibana/kibana:8.7.0-amd64
            state: started
            privileged: false
            env:
              SERVERNAME: kibana
              ELASTICSEARCH_HOSTS: http://192.168.122.10:9200
              ELASTICSEARCH_USERNAME: kibana_system
              ELASTICSEARCH_PASSWORD: Admin1Admin1
            ports:
              - 5601:5601
            network: elk_network
            restart_policy: always

        - name: Run elasticsearch
          containers.podman.podman_container:
            name: elasticsearch
            image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-amd64
            state: started
            privileged: false
            env:
              "discovery.type": single-node
              "cluster.name": docker-cluster
              bootstrap.memory_lock: "true"
              ES_JAVA_OPTS: "-Xms1024m -Xmx2048m"
              ELASTIC_PASSWORD: Admin1Admin1
              KIBANA_PASSWORD: Admin1Admin1
              LICENSE: basic
              # LICENSE=trial
              ES_PORT: "9200"
              KIBANA_PORT: "5601"
              xpack.security.enabled: false
              http.cors.enabled: "true"
              http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
              http.cors.allow-credentials: "true"
            ulimit:
              - "nofile=65535:65535"
              - "memlock=-1:-1"
            ports:
              - 9200:9200
              - 9300:9300
            network: elk_network
            restart_policy: always
            volumes:
              - es-data:/usr/share/elasticsearch/data

  handlers:
    - name: logstash-restart
      containers.podman.podman_container:
        name: logstash
        # state: started
        force_restart: true

    - name: elasticsearch-restart
      containers.podman.podman_container:
        name: elasticsearch
        # state: started
        force_restart: true
