---
- name: Deploy ELK
  hosts: elk
  become: true
  vars:
    service_location: /opt/elk/
  tasks:
    - ansible.builtin.include_role:
        name: geerlingguy.docker
      tags: ["install-docker"]

    - name: Manage service
      tags: ["containers"]
      block:
        - name: Copy files
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ service_location }}"
          with_fileglob:
            - "files/elk/*"
          notify:
            - elk-restart

        - name: Create and start ELK services
          ansible.builtin.shell:
            cmd: docker compose up -d
            chdir: "{{ service_location }}"
          register: output

        - ansible.builtin.debug:
            var: output

  handlers:
    - name: elk-restart
      ansible.builtin.shell:
        cmd: docker compose restart
        chdir: "{{ service_location }}"
