---
- name: Deploy Damn Vulnerable Web Application
  hosts: dvwa
  become: true
  vars:
    service_location: /opt/dvwa
  tasks:
    - name: Update cache
      tags: ["install-docker"]
      ansible.builtin.package:
        update_cache: true

    - ansible.builtin.include_role:
        name: geerlingguy.docker
      tags: ["install-docker"]

    - name: Deploy containers
      tags: ["containers"]
      block:
        - name: Create logs directory
          ansible.builtin.file:
            path: /var/log/nginx
            state: directory
            owner: 65532
            group: 65532
            mode: "0755"

        - name: Move files
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ service_location }}/"
          with_fileglob:
            - files/dvwa/*
          notify:
            - dvwa-restart

        - name: Move Nginx error files
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ service_location }}/nginx_html/"
          with_fileglob:
            - files/dvwa/nginx_html/*
          notify:
            - dvwa-restart

        - name: Create and start DVWA services
          ansible.builtin.shell:
            cmd: docker compose up -d
            chdir: "{{ service_location }}"
          register: output

        - ansible.builtin.debug:
            var: output

  handlers:
    - name: dvwa-restart
      ansible.builtin.shell:
        cmd: docker compose restart
        chdir: "{{ service_location }}"
